run:
  timeout: 10m

linters:
  disable-all: false
  disable:
    - golint # deprecated
    - interfacer # deprecated
    - scopelint # deprecated
    - nakedret
    - nolintlint
    - varnamelen
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - misspell
    - wsl
    - tparallel
    - exhaustive
    - asciicheck
    - exportloopref
    - gomnd
    - goerr113
    - dupl
    - goprintffuncname
    - whitespace
    - revive
    - varcheck
    - nestif
    - nilnil

linters-settings:
  dogsled:
    max-blank-identifiers: 3

  maligned:
    suggest-new: true

  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false

  dupl:
    threshold: 150 # minimal duplicate size

  exhaustive:
    default-signifies-exhaustive: false

  funlen:
    lines: 100 # maximum count of code lines
    statements: 50 # maximum count of code lines

  goconst:
    min-len: 2 # length of repeating string
    min-occurrences: 2 # number of occurrences of string

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 25 # cyclical complexity

  goimports:
    local-prefixes: "github.com/persistenceOne/persistenceBridge"

  gomnd:
    settings:
      mnd:
        checks: [argument,case,condition,return] # don't include the "operation" and "assign"

  govet:
    check-shadowing: true # report about shadowed variables
    settings: # settings per analyzer
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - github.com/persistenceOne/persistenceBridge/utilities/logging.Fatal
          - github.com/persistenceOne/persistenceBridge/utilities/logging.Error
          - github.com/persistenceOne/persistenceBridge/utilities/logging.Warn
          - github.com/persistenceOne/persistenceBridge/utilities/logging.Info
          - github.com/persistenceOne/persistenceBridge/utilities/logging.Debug

  lll:
    line-length: 160

  misspell:
    locale: US

  wsl:
    allow-trailing-comment: true
    allow-cuddle-declarations: false

  nestif:
    min-complexity: 41

service:
  golangci-lint-version: 1.43.0
