// generated by deep-copy --type config -o ./types_copy_gen.go ./types.go; DO NOT EDIT.

package configuration

// DeepCopy generates a deep copy of config
func (o config) DeepCopy() config {
	var cp config = o
	if o.Kafka.Brokers != nil {
		cp.Kafka.Brokers = make([]string, len(o.Kafka.Brokers))
		copy(cp.Kafka.Brokers, o.Kafka.Brokers)
	}
	return cp
}
