name: Lint
# Lint runs golangci-lint over the entire Gaia repository
# This workflow is run on every pull request and push to master
# The `golangci` job will pass without running if no *.{go, mod, sum} files have been modified.
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  generate:
    test:
      name: check-generate
      runs-on: ubuntu-latest
      steps:
        - name: Install Go
          uses: actions/setup-go@v2
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Get dependancies
          run: make deps
        - name: Generate
          run: make generate
        - name: Get generate diff
          uses: technote-space/get-diff-action@v5
        - name: Check generate diff
          run: exit(1)
          if: !env.GIT_DIFF

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERN: |
            .go
            .mod
            .sum
      - uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.43.0
        if: "env.GIT_DIFF != ''"